//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YelCreative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int Id_About { get; set; }
        public string Content_About { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Current_Position { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string City { get; set; }
        public Nullable<int> Age { get; set; }
        public string Degree { get; set; }
    }
}
