//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YelCreative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id_Service { get; set; }
        public string Service_Name { get; set; }
        public string Content_Service { get; set; }
    }
}
