//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YelCreative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int Id_Skill { get; set; }
        public string Skill_Name { get; set; }
        public Nullable<int> Skill_Value { get; set; }
    }
}
