//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YelCreative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id_User { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public string Picture { get; set; }
        public string Full_Name { get; set; }
        public int Id_Role { get; set; }
        public string Image_Path { get; set; }
        public byte[] Image_Byte { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
